# BeluTales Streamlit Configuration
# Safe theme defaults that work with our premium CSS

[theme]
base="dark"
primaryColor="#89c2ff"
backgroundColor="#0f1329"
secondaryBackgroundColor="#151a3a"
textColor="#f7f8ff"

[server]
# Optional performance settings
enableCORS = false
enableXsrfProtection = false

[browser]
# Prevent browser from collecting usage stats
gatherUsageStats = false
